config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  # micropost一件につきimage一件とする
  has_one_attached :image
  # データベースから要素を取り出すとき降順にする
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: {maximum: 140 }
  validates :user_id, presence: true
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], 
                                    message: "must be a valid image format"},
                    size:         { less_than: 5.megabytes, 
                                    message: "should be less than 5MB" }
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(microposts_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = "投稿しました"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:succecc] = "投稿を削除しました"
    # referrerは一つ前のURLを返す
    redirect_to request.referrer || root_url
  end

  private

    def microposts_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%# <%= image_tag micropost.display_image if micropost.image.attached? %>
    <%= image_tag micropost.image if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%#= link_to "delete", micropost_path(micropost), method: :delete, data: {confirm: "本当に削除しますか？"} %>
      <%= link_to "delete", micropost, method: :delete, data: {confirm: "本当に削除しますか？"} %>
    <% end %>
  </span>
</li>